### ISSUE TITLE
 The "loss" index did not decline

### ISSUE THREAD

**Issue by WEIZHIHONG720** [xuyu0010/ARID_UG2_2.2#1]
Thank you for your work!  But I have some questions . The "loss" index did not decline ? I don't seem to see lighting enhancements to the "ARID" dataset in your code .

**Comment by xuyu0010** [comment]
Hi, thank you for your interest. This code only serves as a starting code for the UG2 competition 2022 track 2, so it's only a code that "could run" not a code that could run well. For the lighting enhancements, you may refer to https://github.com/dawnlh/awesome-low-light-image-enhancement, the enhancements can be simply performed on a per-frame basis.
