### ISSUE TITLE
Semi-supervised learning algorithm

### ISSUE THREAD

**Issue by WEIZHIHONG720** [xuyu0010/ARID_UG2_2.2#2]
Thank you for your outstanding work! I want to know where the semi-supervised learning algorithm is embodied? Looking forward to your reply, thank you!

**Comment by xuyu0010** [comment]
Hi, we apply transfer learning algorithms to leverage labeled source data to the unlabeled target data. You may consider TL as a corner case for SSL.

**Comment by WEIZHIHONG720** [comment]
DANN? ok! Thank you !




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuyu0010/ARID_UG2_2.2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月17日(星期四) 晚上10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xuyu0010/ARID_UG2_2.2] Semi-supervised learning algorithm (Issue #2)





 
Hi, we apply transfer learning algorithms to leverage labeled source data to the unlabeled target data. You may consider TL as a corner case for SSL.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
